spring:
  application:
    name: code-qr-generator

infrastructure:
  path_directory: /softtek/qr/
  csv_directory: /csv/
  qr_directory: /test/
  zip_directory: /compress/
  csv_file: users.csv
  zip_file: qrsCompressed.zip

definition:
  qr:
    width: 350
    height: 350
    type: png